export const FIRST_REQUEST = 'FIRST_REQUEST';
export const FIRST_SUCCESS = 'FIRST_SUCCESS';
export const FIRST_FAIL = 'FIRST_FAIL';

export const SECOND_REQUEST = 'SECOND_REQUEST';
export const SECOND_SUCCESS = 'SECOND_SUCCESS';
export const SECOND_FAIL = 'SECOND_FAIL';
